# Generated by Django 3.2.7 on 2021-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth',
            field=models.JSONField(blank=True, null=True, verbose_name='OAuth 2.0 data'),
        ),
    ]
