---
services:
  django:
    profiles: ['dev']
    build:
      context: ./
      dockerfile: ./devops/docker/django/Dockerfile
      args:
        IMAGE: python:${PYTHON_IMAGE_VERSION:-latest}
    entrypoint: /app/devops/docker/django/entrypoint.sh
    command: pipenv run serve 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - CACHE_LOCATION=redis://redis:${REDIS_PORT}/1
      - CELERY_BROKER_URL=redis://redis:${REDIS_PORT}/2

  celery:
    profiles: ['dev']
    build:
      context: ./
      dockerfile: ./devops/docker/django/Dockerfile
      args:
        IMAGE: python:${PYTHON_IMAGE_VERSION:-latest}
    entrypoint: /app/devops/docker/django/entrypoint.sh
    command: pipenv run celery
    volumes:
      - .:/app
    depends_on:
      - django
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - CACHE_LOCATION=redis://redis:${REDIS_PORT}/1
      - CELERY_BROKER_URL=redis://redis:${REDIS_PORT}/2

  db:
    profiles: ['db', 'dev']
    image: ${DB_IMAGE:-postgres}:${DB_IMAGE_VERSION:-latest}
    volumes:
      - mysql_data:/var/lib/mysql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - MYSQL_DATABASE=${DB_NAME:-mydb}
      - MYSQL_HOST=0.0.0.0
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-mysql}
      - POSTGRES_DB=${DB_NAME:-mydb}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
    ports:
      - '${DB_PORT:-5432}:${DB_PORT:-5432}'

  redis:
    profiles: ['db', 'dev']
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT:-6379}:6379

  mailhog:
    profiles: ['mailhog', 'dev']
    image: mailhog/mailhog
    ports:
       - 1025:1025  # smtp server
       - 8025:8025  # web ui

volumes:
  mysql_data:
  postgres_data:
  redis_data:
